# Generated by tools/bash_builds.py; source SHA-256 901fc5809a5e5a57b92df168b33ba07e834996199b19a871a4b6dd15c7ac41a2. DO NOT EDIT.
"""Generated host-preparation consumer; only measured entries are present."""
import hashlib
import json
import os
from pathlib import Path
import stat

_TABLE = '{"builds":{},"version":1}'


def lookup(path: str, expected_digest: str, target: dict[str, str], inputs: dict[str, str]) -> dict:
    """inputs contains current manifest-verified adapter/trusted-input hashes."""
    resolved = Path(path).resolve(strict=True)
    if not stat.S_ISREG(resolved.stat().st_mode):
        raise ValueError("nonregular Bash")
    descriptor = os.open(resolved, os.O_RDONLY | os.O_NONBLOCK | os.O_NOFOLLOW)
    with os.fdopen(descriptor, "rb") as stream:
        if not stat.S_ISREG(os.fstat(stream.fileno()).st_mode):
            raise ValueError("nonregular Bash")
        observed = hashlib.file_digest(stream, "sha256").hexdigest()
    entry = json.loads(_TABLE)["builds"].get(observed)
    if observed != expected_digest or entry is None:
        raise ValueError("unknown or mismatched Bash build")
    build = entry["candidate"]
    if build["target"] != target:
        raise ValueError("wrong Bash target")
    if str(Path(path).resolve(strict=True)) != build["resolved_path"]:
        raise ValueError("wrong resolved Bash path")
    if build["system_rc"] != "none":
        try:
            os.lstat(build["system_rc"])
        except FileNotFoundError:
            pass
        else:
            raise ValueError("present system Bash rc")
    if entry["qualification"]["adapter_inputs"] != inputs:
        raise ValueError("adapter or trusted inputs require requalification")
    return entry
