defaults:
  - studio_schema
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

recording: null
script_params: {}
action: build
step: null
output_format: text
verbose: false
load_env_file: true
env_file: .env
env_override: false
output: null
cast: null
timeline: null
surface: null
dry_run: false
headed: false
force: false
timestamps: true
allow_mismatch: false
run_id: null
runs_since: null
runs_limit: 10

studio:
  keep_output_dir: true

hydra:
  output_subdir: null
  run:
    dir: ${studio_run_dir:${action},${step},${dry_run},${recording},${now:%Y%m%d-%H%M%S}}
  job:
    chdir: false
