defaults:
  - studio_schema
  - reploy/controller@reploy.controller: omegaflow
  - reploy/envoy@reploy.workload: default
  - reploy/app@reploy.workload: internal-demo
  - _self_
  - optional /.omegaflow@_here_: config
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  searchpath:
    - file://.
  output_subdir: null
  run:
    dir: ${studio.run_dir}
  job:
    name: omegaflow
    chdir: false
