// Generated by tools/bash_builds.py; source SHA-256 901fc5809a5e5a57b92df168b33ba07e834996199b19a871a4b6dd15c7ac41a2. DO NOT EDIT.
package bashbuild

const tableJSON = "{\"builds\":{},\"version\":1}"
